name: Flexy Pixel CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  Unit-test:
    name: Run unit tests on PR in master
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 17 }

        # Simple build
      - name: Assemble Debug
        run: ./gradlew assembleDebug

        # Unit tests
      - name: Run unit tests
        run: ./gradlew test

        # Espresso auto tests
      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          script: ./gradlew connectedCheck