name: Flexy Pixel CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  Unit-test:
    name: Run unit tests on PR in master
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 17 }
      - name: Assemble Debug
        run: ./gradlew assembleDebug
      - name: Run unit tests
        run: ./gradlew test
      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86
          profile: Nexus 6
        run: ./gradlew connectedAndroidTest